Illuminate/Controllers/BranchController.cs
using AutoMapper;
using Illuminate.Async.DTO.Branch;
using Illuminate.Components.Authorization;
using Illuminate.DataAccess.Interfaces;
using Illuminate.DataAccess.Models;
using Illuminate.ViewModels.Branch;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Illuminate.Controllers
{
    [AuthorizeRoles(true, UserPermissions.ManageBranches)]
    public class BranchController : Controller
    {
        private IMapper _mapper;

        private readonly IUnitOfWork _unitOfWork;

        public BranchController(IMapper mapper, 
            IUnitOfWork unitOfWork)
        {
            _mapper = mapper;
            _unitOfWork = unitOfWork;
        }

        /// <summary>
        /// list all branches
        /// </summary>
        /// <returns></returns>
        public async Task<ViewResult> Index()
        {
            var collection = await _unitOfWork.Branches.AllAsync();
            return View(new ListingViewModel
            {
                Branches = (List<Branches>) collection 
            });
        }

        /// <summary>
        /// create view
        /// </summary>
        /// <returns></returns>
        public ViewResult Create()
        {
            return View(new CreateUpdateBranchViewModel());
        }

        /// <summary>
        /// http post/create function for Create()
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OnCreate(CreateUpdateBranchViewModel viewModel)
        {
            if(!ModelState.IsValid)
                return View("Create", viewModel);

            var model = new Branches();
            _mapper.Map(viewModel, model);
            _unitOfWork.Branches.Add(model);
            await _unitOfWork.SaveAsync();

            return RedirectToAction("Manage", new { id = model.Id });
        }

        /// <summary>
        /// view branch
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Manage(int id)
        {
            var model = await _unitOfWork.Branches.FindAsync(x => x.Id == id);
            if (model == null)
                return RedirectToAction("Index");

            var viewModel = _mapper.Map<CreateUpdateBranchViewModel>(model);
            return View(viewModel);
        }

        /// <summary>
        /// update function for Manage()
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(CreateUpdateBranchViewModel viewModel)
        {
            if(!ModelState.IsValid)
                return View("Manage", viewModel);

            var model = await _unitOfWork.Branches.FindAsync(x => x.Id == viewModel.Id);
            _mapper.Map(viewModel, model);
            await _unitOfWork.SaveAsync();

            return RedirectToAction("Manage", new { id = model.Id });
        }

        /// <summary>
        /// set (negate) branch IsActive value
        /// </summary>
        /// <param name="branch"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<RedirectToActionResult> SetActive(Branches branch)
        {
            var model = await _unitOfWork.Branches.GetBranchStateAsync(x => x.Id == branch.Id);
            if (model == null)
                return RedirectToAction("Index");

            model.IsActive = !model.IsActive;
            await _unitOfWork.SaveAsync();

            return RedirectToAction("Index");
        }

        /// <summary>
        /// NOTE: TEMPORARY METHOD FOR LISTING BRANCHES. 
        /// </summary>
        /// <param name="id">except specified branchId</param>
        /// <returns></returns>
        [AuthorizeRoles(true, UserPermissions.MoveStocks)]
        [HttpPost]
        [ValidateAntiForgeryToken]        
        public async Task<JsonResult> GetAll([FromBody] GetAllExceptDto dto)
        {
            return Json(await _unitOfWork.Branches.AllExceptAsync(dto.Id));
        }
    }
}

Illuminate/Controllers/SettingsController.cs
using Illuminate.Components.Authorization;
using Illuminate.Components.Settings;
using Illuminate.DataAccess.Models;
using Illuminate.ViewModels.Settings;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Illuminate.Controllers
{
    public class SettingsController : Controller
    {
        private readonly ISettingsProxy<Settings> _settingsProxy;

        public SettingsController(ISettingsProxy<Settings> settingsProxy)
        {
            _settingsProxy = settingsProxy;
        }

        public async Task<IActionResult> Index()
        {
            await _settingsProxy.CreateOrUpdateAppSettingAsync(DataAccess.Models.Enums.SettingsAttributes.AppName, "Clarity", true);
            return View();
        }

        [AuthorizeRoles(true, UserPermissions.EditAppSettings)]
        public IActionResult Admin()
        {
            return View(new AppSettingsViewModel());
        }
    }
}

Illuminate/Controllers/UserController.cs
using AutoMapper;
using Illuminate.Async.DTO.User;
using Illuminate.Async.Responses.Branch;
using Illuminate.Async.Responses.User;
using Illuminate.Components.Authorization;
using Illuminate.DataAccess.Interfaces;
using Illuminate.DataAccess.Models;
using Illuminate.DataAccess.Models.Joins;
using Illuminate.ViewModels.User;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Illuminate.Controllers
{
    [AuthorizeRoles(true, UserPermissions.ManageUsers)]
    public class UserController : Controller
    {
        private readonly IMapper _mapper;

        private readonly IUnitOfWork _unitOfWork;

        private readonly UserManager<User> _userManager;

        public UserController(IMapper mapper,
            IUnitOfWork unitOfWork,
            UserManager<User> userManager)
        {
            _mapper = mapper;
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }

        /// <summary>
        /// list all uers
        /// </summary>
        /// <returns></returns>
        public async Task<ViewResult> Index()
        {
            var collection = await _unitOfWork.Users.ForListingAsync();
            var mappedCollection = _mapper.Map<IEnumerable<User>, List<UserViewModel>>(collection);
            
            return View(new ListViewModel {
                Users = mappedCollection
            });
        }

        /// <summary>
        /// view user profile
        /// Identity/Account/Manage will be used for personal profiles
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Profile(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) // redirect if not found
                return RedirectToAction("Index");            

            return View(new UserProfileViewModel
            {
                UpdateViewModel = _mapper.Map<User, UpdateUserViewModel>(user)
            });
        }

        /// <summary>
        /// http post (update) function for Profile()
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(UserProfileViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View("Profile", viewModel);
            
            var user = await _userManager.FindByIdAsync(viewModel.UpdateViewModel.Id);
            user.Email = viewModel.UpdateViewModel.Email;
            user.FirstName = viewModel.UpdateViewModel.FirstName;
            user.LastName = viewModel.UpdateViewModel.LastName;
            user.PhoneNumber = viewModel.UpdateViewModel.PhoneNumber;
            await _unitOfWork.SaveAsync();

            return RedirectToAction("Profile", new { id = viewModel.UpdateViewModel.Id });
        }

        /// <summary>
        /// activate/deactive user account
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        public async Task<IActionResult> SetActive(UserViewModel viewModel)
        {
            var model = await _userManager.FindByIdAsync(viewModel.Id);
            if (model == null)
                return RedirectToAction("Index");

            model.IsActive = !model.IsActive;
            await _userManager.UpdateAsync(model);

            return RedirectToAction("Index");
        }

        /// <summary>
        /// get all users for listing
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<JsonResult> AllUsers()
        {
            var collection = await _unitOfWork.Users.ForAjaxListingAsync();
            return Json(_mapper.Map<List<UsersToBranchEmployee>, List<UserDetailsDto>>((List<UsersToBranchEmployee>) collection));
        }

        /// <summary>
        /// assign user to branch
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> AssignToBranch([FromBody] AssignUserDto viewModel)
        {
            var user = await _userManager.FindByIdAsync(viewModel.UserId);
            if (user == null)
                return Json(new UserNotFoundResponse());

            var branch = await _unitOfWork.Branches.FindAsync(x => x.Id == viewModel.BranchId);
            if (branch == null)
                return Json(new BranchNotFoundResponse());

            if (!viewModel.Remove)
            {
                user.BranchId = viewModel.BranchId;
                await _userManager.UpdateAsync(user);
                return Json(new UserAssignedToBranchResponse(branch.Name, user.FirstName, user.LastName));
            }
            else
            {
                user.BranchId = null;
                await _userManager.UpdateAsync(user);
                return Json(new UserRemovedFromBranchResponse(branch.Name, user.FirstName, user.LastName));
            }
        }
    }
}

Illuminate/Views/Shared/Components/AppName/AppNameViewComponent.cs
using Illuminate.Components.Settings;
using Illuminate.DataAccess.Models;
using Illuminate.ViewModels.Components;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Illuminate.Views.Components.AppName
{
    public class AppNameViewComponent : ViewComponent
    {
        private ISettingsProxy<Settings> _settings;

        public AppNameViewComponent(ISettingsProxy<Settings> settings)
        {
            _settings = settings;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            try
            {
                var appName = await _settings.GetAppSettingAsync(DataAccess.Models.Enums.SettingsAttributes.AppName);

                return View("Default", new AppNameViewModel()
                {
                    NameLarge = appName.Value,
                    NameMini = appName.Value[0]
                });
            }
            catch (Exception e)
            {
                throw e;
            }
        }
    }
}

Illuminate/Views/Shared/Components/PageTitleViewComponent.cs
using Illuminate.Components.Settings;
using Illuminate.DataAccess.Models;
using Illuminate.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System.Threading.Tasks;

namespace Illuminate.Views.Components
{
    public class PageTitleViewComponent : ViewComponent
    {
        private readonly ISettingsProxy<Settings> _settings;

        public PageTitleViewComponent(ISettingsProxy<Settings> settings)
        {
            _settings = settings;
        }

        public async Task<string> InvokeAsync(ViewDataDictionary viewData)
        {
            var appName = await _settings.GetAppSettingAsync(DataAccess.Models.Enums.SettingsAttributes.AppName);

            // this component is created due to the difference between razor pages (mvvm) and views (mvc)
            // this acts like an adapter to create page title
            string pageTitle;
            if (viewData.Model is BaseViewModel)
            {
                BaseViewModel viewModel = (BaseViewModel)viewData.Model;
                pageTitle = viewModel.PageTitle;
            }
            else
            {
                pageTitle = viewData["PageTitle"].ToString();
            }

            return $"{pageTitle} | {appName.Value}";
        }
    }
}

Illuminate/Views/Shared/Components/UserIdentityViewComponent.cs
using Illuminate.DataAccess.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;

namespace Illuminate.Views.Components
{
    public class UserIdentityViewComponent
    {
        private readonly IHttpContextAccessor _httpContext;

        private readonly UserManager<User> _userManager;

        public UserIdentityViewComponent(IHttpContextAccessor httpContext, UserManager<User> userManager)
        {
            _httpContext = httpContext;
            _userManager = userManager;
        }

        public async Task<string> InvokeAsync()
        {
            var user = await _userManager.GetUserAsync(_httpContext.HttpContext.User);

            if (string.IsNullOrEmpty(user.FirstName))
                return user.Email;

            return $"{user.FirstName} {user.LastName}";
        }
    }
}

Illuminate/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 1
    </div>
    <strong>Copyright © 2018 <a href="mailto:rplansangan@gmail.com">Ralphael Lansangan</a>.</strong> All rights
    reserved.
</footer>

Illuminate/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@await Component.InvokeAsync("PageTitle", ViewData)</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/ionicons.min.css" />
    <link rel="stylesheet" href="~/css/AdminLTE.min.css" />
    <link rel="stylesheet" href="~/css/_all-skins.min.css" />
    <link rel="stylesheet" href="~/css/app.css" />
    <environment include="Development">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>
    @RenderSection("Styles", required: false)
</head>
<body class="skin-blue sidebar-mini">
    <div class="wrapper">
        <partial name="_CookieConsentPartial" />
        <partial name="_TopBar" />
        <partial name="_SideBar" />
        @RenderBody()
        <partial name="_Footer" />
        @Html.AntiForgeryToken()
    </div>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.slimscroll.min.js"></script>
    <script src="~/js/fastclick.js"></script>
    <script src="~/js/adminlte.min.js"></script>
    <environment include="Development">
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
    <script src="~/app/topnav.js"></script>
</body>
</html>

Illuminate/Views/Shared/_SideBar.cshtml
@{ 
    var isAdmin = User.IsInRole(UserPermissions.Admin);
}
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar" style="height: auto;">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>@await Component.InvokeAsync("UserIdentity")</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu tree" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li>
                <a href=@Url.Action("Index", "Home")>
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
            </li>
            @if (User.IsInRole(UserPermissions.ManageBranches) || isAdmin)
            {
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-building"></i>
                        <span>Branches</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        @if (User.IsInRole(UserPermissions.CreateUpdateStocks) || isAdmin)
                        {
                            <li>
                                <a href=@Url.Action("Create", "Branch")>
                                    <i class="fa fa-circle-o"></i>
                                    <span>New Branch</span>
                                </a>
                            </li>
                        }
                        <li>
                            <a href=@Url.Action("Index", "Branch")>
                                <i class="fa fa-circle-o"></i>
                                <span>All Branches</span>
                            </a>
                        </li>
                    </ul>
                </li>
            }
            @{
                var allowCreateStock = User.IsInRole(UserPermissions.CreateUpdateStocks);
                var allowListStocks = User.IsInRole(UserPermissions.ListAndViewStocks);
            }
            @if (allowCreateStock || allowListStocks || isAdmin)
            {
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-cubes"></i>
                        <span>Stocks</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        @if (allowCreateStock || isAdmin)
                        {
                            <li>
                                <a href=@Url.Action("Create", "Stock")>
                                    <i class="fa fa-circle-o"></i>
                                    <span>New Stock</span>
                                </a>
                            </li>
                        }
                        @if (allowListStocks || isAdmin)
                        {
                            <li>
                                <a href=@Url.Action("Index", "Stock")>
                                    <i class="fa fa-circle-o"></i>
                                    <span>All Stocks</span>
                                </a>
                            </li>
                        }
                    </ul>
                </li>
            }
            @{
                var allowUserMgmt = User.IsInRole(UserPermissions.ManageUsers);
                var allowPermissionsMgmt = User.IsInRole(UserPermissions.ManagePermissions);
            }
            @if (allowUserMgmt || allowPermissionsMgmt || isAdmin)
            {
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-users"></i>
                        <span>Users</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        @if (allowUserMgmt || isAdmin)
                        {
                            <li>
                                <a href="/Identity/Account/Register">
                                    <i class="fa fa-circle-o"></i>
                                    <span>Register User</span>
                                </a>
                            </li>
                            <li>
                                <a href=@Url.Action("Index", "User")>
                                    <i class="fa fa-circle-o"></i>
                                    <span>All Users</span>
                                </a>
                            </li>
                        }
                        @if (allowPermissionsMgmt || isAdmin)
                        {
                            <li>
                                <a href=@Url.Action("Index", "Permissions")>
                                    <i class="fa fa-circle-o"></i>
                                    <span>Permissions</span>
                                </a>
                            </li>
                        }
                    </ul>
                </li>
            }
            @{ 
                var allowAppSettings = User.IsInRole(UserPermissions.EditAppSettings);
            }
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-cog"></i>
                    <span>Settings</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a href=@Url.Action("Index", "Settings")>
                            <i class="fa fa-circle-o"></i>
                            <span>User Settings</span>
                        </a>
                    </li>
                    @if(allowAppSettings || isAdmin)
                    {
                        <li>
                            <a href=@Url.Action("Admin", "Settings")>
                                <i class="fa fa-circle-o"></i>
                                <span>App Settings</span>
                            </a>
                        </li>
                    }
                </ul>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

Illuminate/Views/Shared/_TopBar.cshtml
<header class="main-header">
    <!-- Logo -->
    <a asp-controller="Home" asp-action="Index" class="logo">
        @await  Component.InvokeAsync("AppName")
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <div id="top-nav-container" class="navbar-custom-menu">            
        </div>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!--<img src="../../dist/img/user2-160x160.jpg" class="user-image" alt="User Image">-->
                        <span class="hidden-xs">@await  Component.InvokeAsync("UserIdentity")</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <!--<img src="../../dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">-->

                            <p>
                                @await Component.InvokeAsync("UserIdentity")
                                <small>Member since Nov. 2012</small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <!--<li class="user-body">
                            <div class="row">
                                <div class="col-xs-4 text-center">
                                    <a href="#">Followers</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Sales</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Friends</a>
                                </div>
                            </div>
                        </li>-->
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a class="btn btn-default btn-flat" href="/Identity/Account/Manage">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a class="btn btn-primary btn-flat" href="/Identity/Account/Logout">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <!--<li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>-->
            </ul>
        </div>
    </nav>
</header>